name: Deploy
on:
  push:
    branches:
      - main
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
  APP_VERSION: '2.4.0'
  SCHEME_NAME: 'EhPanda'
  ALTSTORE_JSON_PATH: './AltStore.json'
  BUILDS_PATH: '/tmp/action-builds'
  FILTER_PATH: './actions-tool/ReleaseNotesFilter'
  ARCHIVE_PATH: '/tmp/action-builds/EhPanda.xcarchive'
  IPA_OUTPUT_PATH: '/tmp/action-builds/EhPanda.ipa'
  DIS_P12_PATH: '/tmp/action-builds/dis.p12'
  APP_DIS_PROVISION_PATH: '/tmp/action-builds/app_dis.mobileprovision'
  SHARE_EXTENSION_DIS_PROVISION_PATH: '/tmp/action-builds/share_extension_dis.mobileprovision'
jobs:
  Deploy:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install rswift
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Decode certificates & provisioning profiles
        run: |
          mkdir $BUILDS_PATH
          echo -n ${{ secrets.DIS_P12 }} | base64 -d -o $DIS_P12_PATH
          echo -n ${{ secrets.APP_DIS_PROVISION }} | base64 -d -o $APP_DIS_PROVISION_PATH
          echo -n ${{ secrets.SHARE_EXTENSION_DIS_PROVISION }} | base64 -d -o $SHARE_EXTENSION_DIS_PROVISION_PATH
      - name: Install certificates
        run: |
          KEY_CHAIN=action-builds.keychain-db
          P12_PASSWORD="${{ secrets.P12_PASSWORD }}"
          security create-keychain -p $P12_PASSWORD $KEY_CHAIN
          security default-keychain -s $KEY_CHAIN
          security unlock-keychain -p $P12_PASSWORD $KEY_CHAIN
          security set-keychain-settings -t 3600 -u $KEY_CHAIN
          security import $DIS_P12_PATH -k $KEY_CHAIN -P $P12_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k $P12_PASSWORD ~/Library/Keychains/$KEY_CHAIN
          security list-keychains
          security find-identity -p codesigning ~/Library/Keychains/$KEY_CHAIN
      - name: Install provisioning profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          app_dis_uuid=`grep UUID -A1 -a $APP_DIS_PROVISION_PATH | grep -io "[-A-F0-9]\{36\}"`
          share_extension_dis_uuid=`grep UUID -A1 -a $SHARE_EXTENSION_DIS_PROVISION_PATH | grep -io "[-A-F0-9]\{36\}"`
          cp $APP_DIS_PROVISION_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$app_dis_uuid.mobileprovision
          cp $SHARE_EXTENSION_DIS_PROVISION_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$share_extension_dis_uuid.mobileprovision
          ls ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Xcode archive
        run: xcodebuild archive -destination 'generic/platform=iOS' -configuration Release
          -scheme ${{ env.SCHEME_NAME }} -archivePath ${{ env.ARCHIVE_PATH }}
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - name: Export .ipa file
        run: xcodebuild -exportArchive -archivePath ${{ env.ARCHIVE_PATH }}
          -exportPath ${{ env.BUILDS_PATH }} -exportOptionsPlist ./actions-tool/ExportOptions.plist
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: ${{ env.IPA_OUTPUT_PATH }}
      - name: Upload to ASC
        run: |
          xcrun altool --upload-app --type ios \
            --file ${{ env.IPA_OUTPUT_PATH }} \
            --username "${{ secrets.APPSTORE_CONNECT_USERNAME }}" \
            --password "${{ secrets.APPSTORE_CONNECT_PASSWORD }}" --verbose
